#' An internal function for counting multigrams. Accepts a collsDB and returns a tibble containing collocate counts
#' 
#' @param collsDB A collocates list, combined with relevant counts, generated by save_collocates
#' @include CollDB.R
#' @import tibble dplyr
#' @importFrom stringr str_count str_replace_all
#'
count_multigrams <- function(collsDB, ngram){
      
      all_locs <- collsDB[[7]]
      # Convert locations into words
      texts <- lapply(all_locs, function(x)
            collsDB$doc_table[x,])
      # Return the node text
      texts <- lapply(texts, function(x)
            tibble(word = str_replace_all(x$word,
                                   collsDB$node_hash, 
                                   collsDB$node)))
      
      # An internal function to create a list of ngrams from texts
      ngramiser <- function(texts, ngram){
            vectorised <- texts %>% 
                  select(word) %>% 
                  sapply(as.character) %>% 
                  as.vector
            ngrams <- tibble(vectorised) %>%
                  tidytext::unnest_tokens(word,
                                          vectorised,
                                          token = "ngrams",
                                          n = ngram)
            return(ngrams)
      }
      #Unnest for requisite ngram for each element in the list
      colls <- lapply(texts, function(x) ngramiser(x, ngram))
      
      # Turn the colls list into a tibble with counts
      colls_bound <- bind_rows(colls) %>%
            table(.) %>%
            tibble(word = names(.), collss = .)
      # Turn the colls list into a vector
      colls_vector <- colls_bound %>%
            select(word) %>%
            sapply(as.character) %>%
            as.vector
      # Count all the collocates across the text
      count_all_terms <- function(collsDB, colls_vector){
        # vectorise the whole document
            all_words_vectorised <- collsDB$doc_table %>%
                  select(word) %>%
                  sapply(as.character) %>%
                  as.vector %>% 
                  paste(., sep = " ", collapse = " ") %>%
                  str_replace_all(., collsDB$node_hash, collsDB$node) # <-- replace hashed node
            # Count the ngrams
            counted_ngrams <- str_count(all_words_vectorised, colls_vector)
            return(counted_ngrams)
      }
      count_ngrams_all_text <- count_all_terms(collsDB, colls_vector)
      
      multigram_counts <- bind_cols(colls_bound, as_tibble(count_ngrams_all_text))
      
      colnames(multigram_counts) <- c("word", "coll_freq", "doc_freq")
      return(multigram_counts)
}