#' An internal function for counting unigrams. Accepts a collsDB and returns a tibble containing collocate counts
#' 
#' @param collsDB A collocates list, combined with relevant counts, generated by save_collocates
#' @include CollDB.R 
#' @import tibble dplyr
#'
count_unigrams <- function(collsDB){
      # Convert duplicates, locations below 1 and above the word count to NA
all_locs <- collsDB[[7]] %>% unlist(.)
# Convert locations into words
coll_counts <- collsDB$doc_table[all_locs,] %>%
      table(.) %>%
      tibble(word = names(.), coll_count = .)



return(coll_counts)
}

# Leaving this here for offering locational collocate data
#left_counts <- doc$doc_table[left_locs, ] %>%
#     table(.) %>% 
#    tibble(word = names(.), count = .)  

#right_counts <- doc$doc_table[right_locs, ] %>%
#     table(.) %>% 
#    tibble(word = names(.), count = .)
#}