#' A simple function for counting collocates
#' 
#' @param collsDB A collocates list, combined with relevant counts, generated by save_collocates
#' 
count_collocates <- function(collsDB){
      # Convert duplicates, locations below 1 and above the word count to NA
left_locs <- collsDB[[1]] %>% unlist(.)
right_locs <- collsDB[[1]] %>% unlist(.)
all_locs <- c(left_locs, right_locs)
# Convert duplicates, locations below 1 and above the word count to NA
all_locs[duplicated(all_locs)] <- NA
all_locs[all_locs < 1] <- NA
all_locs[all_locs > nrow(collsDB$doc_table)] <- NA

# Convert locations into words
coll_counts <- collsDB$doc_table[all_locs,] %>%
      table(.) %>%
      tibble(word = names(.), coll_count = .)

return(coll_counts)
}

# Leaving this here for offering locational collocate data
#left_counts <- doc$doc_table[left_locs, ] %>%
#     table(.) %>% 
#    tibble(word = names(.), count = .)  

#right_counts <- doc$doc_table[right_locs, ] %>%
#     table(.) %>% 
#    tibble(word = names(.), count = .)
#}