#' An internal function for returning a list of locations, including notes and running all contiguous words together
#'
#' @param collsDB A collocates list, combined with relevant counts, generated by save_collocates
#' @include CollDB.R
#' @import tibble dplyr

mins_to_maxs <- function(collDBdoc){
 # Put all the numbers in each sequence in a vector, including the node and remove NAs
 collocates_seq <- lapply(seq_along(1:length(collDBdoc[[1]])),
                          function(a)
                                c(collDBdoc[[1]][[a]],collDBdoc[[2]][[a]])) %>%
       lapply(., na.omit) %>%
       lapply(., function(a) {
             a <- min(a):max(a)
             }) %>%
       unlist
 # Remove duplicates if required
 dups <- collocates_seq %>% duplicated %>% which(. == TRUE)
 if(isTRUE(length(dups) != 0)){
 collocates_seq <- collocates_seq[-dups]}

 # Is a number in sequence with the previous number?

 number_in_sequence <- function(number, number_before){
      sequenced <- ifelse(((number-1 == number_before) == TRUE), yes = TRUE, no = FALSE)
      return(sequenced)
 }
 # Apply the function to collocates_seq

 sequence.tf <- sapply(seq_along(1:length(collocates_seq)),
                       function(a)
                             number_in_sequence(collocates_seq[a], collocates_seq[a-1]))
 sequence.tf[1] <- TRUE
 # Find the first and last location of each collocation sequence and apply to the collocates_seq vector
 collocate_sequence_start <- as.integer(which(sequence.tf == FALSE))
 collocate_sequence_end <- collocate_sequence_start - 1
 # Add first and last numerals
 collocate_sequence_start <- c(1, collocate_sequence_start)
 collocate_sequence_end <- c(collocate_sequence_end, as.integer(length(collocates_seq)))

 collocates.l <- lapply(seq_along(1:length(collocate_sequence_end)),
                        function(x)
                              collocates_seq[collocate_sequence_start[x]:collocate_sequence_end[x]])

 return(collocates.l)
}
